"""empty message

Revision ID: 213609af33b1
Revises: 5b3647cb326a
Create Date: 2022-05-20 17:04:27.888338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213609af33b1'
down_revision = '5b3647cb326a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imovel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('proprietario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imovel')
    # ### end Alembic commands ###
