"""empty message

Revision ID: 354fa5406e3a
Revises: 
Create Date: 2022-04-26 02:05:26.537086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354fa5406e3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquilinos')
    # ### end Alembic commands ###
