"""empty message

Revision ID: 5b3647cb326a
Revises: d387e5e5f0e1
Create Date: 2022-05-05 23:39:48.790932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3647cb326a'
down_revision = 'd387e5e5f0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inquilinos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilinos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='inquilinos_pkey')
    )
    op.drop_table('inquilino')
    # ### end Alembic commands ###
