"""empty message

Revision ID: 6de19ca3e297
Revises: d084abf40ffb
Create Date: 2022-05-24 21:59:09.069669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de19ca3e297'
down_revision = 'd084abf40ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluguel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_imovel', sa.String(), nullable=True),
    sa.Column('id_inquilino', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluguel')
    # ### end Alembic commands ###
