"""empty message

Revision ID: d084abf40ffb
Revises: aa9ec6605ef5
Create Date: 2022-05-24 19:42:06.969779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd084abf40ffb'
down_revision = 'aa9ec6605ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aluguel', 'id_inquilino',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('aluguel', 'id_imovel',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('aluguel_id_inquilino_fkey', 'aluguel', type_='foreignkey')
    op.drop_constraint('aluguel_id_imovel_fkey', 'aluguel', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('aluguel_id_imovel_fkey', 'aluguel', 'imovel', ['id_imovel'], ['id'])
    op.create_foreign_key('aluguel_id_inquilino_fkey', 'aluguel', 'inquilino', ['id_inquilino'], ['id'])
    op.alter_column('aluguel', 'id_imovel',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('aluguel', 'id_inquilino',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
